flaskSecret: ""
adminUsername: ""
adminPassword: ""
dbConnectionString: ""
AwsRegion: ap-south-1
s3BucketName: ""
ingressName: "shopsphere-app-ingress"
services:
  frontend:
    deploymentName: frontend-app
    label: "app: frontend"
    imageName: ""
    imageVersion: "1.0"
    hpaName: frontend-hpa
    serviceName: frontend-app-service
    cpu: "100m"
    memory: "128Mi"
  backend:
    deploymentName: backend-app
    label: "app: backend"
    imageName: ""
    imageVersion: "1.0"
    hpaName: backend-hpa
    serviceName: backend-app-service
    cpu: "150m"
    memory: "192Mi"