apiVersion: v1
kind: ConfigMap
metadata:
  name: shopsphere-app-cm
data:
  BACKEND_API_URL: http://{{ .Values.services.backend.serviceName }}:80
  AWS_REGION: {{ .Values.AwsRegion }}
  S3_BUCKET_NAME: {{ .Values.s3BucketName }}