apiVersion: v1
kind: Secret
metadata:
  name: shopsphere-app-secret
type: Opaque
data:
  FLASK_SECRET: {{ .Values.flaskSecret | b64enc }}
  ADMIN_USERNAME: {{ .Values.adminUsername | b64enc }}
  ADMIN_PASSWORD: {{ .Values.adminPassword | b64enc }}
  DB_CONN_STRING: {{ .Values.dbConnectionString | b64enc }}